### PR TITLE
Add CI pipeline

### PR DESCRIPTION
**Pull request by ddugovic**
Free for open source projects, GitHub can lint and test code with every commit:
https://github.com/features/actions

### CODE REVIEW

**Comment by thomasahle** [comment]
This is a good idea, but I don't think this particular script actually does anything?
I think the test scripts first have to be updated to support pytest.

**Comment by ddugovic** [comment]
I have updated the build script to call tests/clean_draws.py directly.

**Comment by thomasahle** [comment]
Let's try it 😁

**Comment by ddugovic** [comment]
#96 might fix some CI errors.

**Pull request merged**
