### PR TITLE
Consider the value of a captured piece in the rotated position

### PR DESCRIPTION
**Pull request by Recursing**
I think that when capturing a piece we should consider the value of a captured piece in the rotated position, to keep the score coherent with the sum of the value of player pieces minus the sum of the value of the opponent pieces in the rotated position.

### CODE REVIEW

**Comment by thomasahle** [comment]
This seems correct to me. Thank you!
There should probably be a unit test to validate this.

**Comment by GregNeto** [comment]
My first post, please forgive my bad english and my even worse programming skills.
Sunfish has given me hours of pleasure, thank you!

The value function never made much sense to me. I score in the move function before "rotate" simply by the addition of the pst-values of the upper pieces minus the addition of the pst-values of the lower pieces.

**Comment by thomasahle** [comment]
GregNeto: I've recently had similar thoughts. The idea of the value method, of course, is to value moves faster. Specially for sorting, since that's done at the very top level of the search tree. However it might still be that other factors dominate the cost. I'll have to do more experiments. What is your experience in terms of sunfish playing strength?

**Comment by GregNeto** [comment]
I am currently adapting the code so that I can play it with black too and human/human and in the future Comp/Comp with different pst's and different search methods. Besides I try to really understand what happens in the search which is quite hard for me because the algorythm is a bit exotic for a beginner (NegaC*/MTD-bi).
From playing sunfish and sunfish selfplay I think that nullmove is not working, it puts the King in check in the endgame etc. I failed with removing nullmove, will study it again
I try to impliment a "simple" alpha beta negamax with tt and iterative deepening without nullmove. but that will take time, I am in the forties and only into Python since 4 weeks .....

**Comment by thomasahle** [comment]
GregNeto, MTD is supposed to be more simple than alpha/beta (only one variable, rather than two ;))

**Comment by GregNeto** [comment]
Well, simple in the eyes of a experienced programmer, at the moment i even fail at implementing a negamax without tt :-)
By the way I do not understand why you changed the captured piece stuff into 119 -j , it seemed to me correct as it was: the value method is used in the move method before the position is rotated and the score reversed, so the capture is considered.
Some small cosmetical stuff:  in line 151 q = self.board[j], so in line 153 q instead of self.board[j]

**Comment by thomasahle** [comment]
As Recursing noted, if we don't rotate the piece square table for opponent pieces, we are not going to value, say a pawn on the 7th rank, the same for both sides. Unit testing showed that this indeed was an issue, and that `119-j` fixed it.

Well spotted about line 153, I'll update that :-)

**Comment by GregNeto** [comment]
hm, i thought the captured piece, for example a pawn on the seventh, added to the score with a value of an **upper** piece which is already correctly (high) valued; will think about it ....

**Comment by GregNeto** [comment]
yes, now i understood: the pawn on the 7th is actually a pawn on the second for the opponent....

**Pull request merged**
