### PR TITLE
Changed UI to print unicode chess pieces

### PR DESCRIPTION
**Pull request by adilosa**
Added a replace_pieces() function that replaces the text-based pieces with unicode chess pieces just before printing the UI. Option for light or dark terminal backgrounds.

screen shot 2014-08-30 at 3 38 38 pm

### CODE REVIEW

**Comment by thomasahle** [comment]
If using ascii internally and unicode for printing turns out to be best,  perhaps one of those tricks: http://stackoverflow.com/questions/1919096/mass-string-replace-in-python could be used to do a short mass replacement. Also, if you have a dict like `{'K':'♚', ...}` you can add `{' ': ' ', '\n':'\n'}` to make it a complete map. That might make the code slightly more simple.

The unicode color switches you describe are pretty nice too. Have you timed whether they have any significant performance overhead compared to the current solution?

**Comment by adilosa** [comment]
Thanks for the StackOverflow link. For some reason, I was overcomplicating it before. 

In this commit, its down to one new line of code and a change to the two `' '.join(pos.board)` lines, which I refactored out into a `format_board(board)` function. Just an explicit piece map, and inline character replace. Due to the `if p in PIECES else c`, I didn't even have to add `{' ': ' ', '\n',: '\n'}` to the pieces map. 

I ended up removing the color-changing option for now to keep things simple. For one, since the terminal color is not known, flipping the colors would require a code change by the user. Assuming the terminal color was known, it could be done either by flipping the internal ascii case just before replacement, or by having a second map/map-altering code.

**Comment by pik** [comment]
This looks great!

**Comment by thomasahle** [comment]
I merged this, it really does look great :-)
However one issue I noticed: Some terminals are light on dark, and others are dark on light - this means on some terminals the colors will look swapped.
Notice for example:

    8 ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖
    7 ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙
    6 . . . . . . . .
    5 . . . . . . . .
    4 . . . . . . . .
    3 . . . . . . . .
    2 ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
    1 ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜
      a b c d e f g h

This looks right on a 'white on black' terminal, but wrong on github. Any ideas?

**Pull request merged**
