### PR TITLE
Fix parsing position uci command

### PR DESCRIPTION
**Pull request by bobtie**
Fixing uci.py to correctly handle a position command like the following one:

 position fen rnbqkbnr/ppp2ppp/8/3pp3/4P3/5P2/PPPP2PP/RNBQKBNR w KQkq - 0 3 moves c2c3

namely when both fen string and move list are specified as allowed by the syntax spefied in UCI protocol:

position [fen  | startpos ]  moves  ....

### CODE REVIEW

**Comment by thomasahle** [comment]
Thank you! This is a good fix.
Can you run commit through autopep8 so we get consistent spacing around `=` and such?

**Comment by thomasahle** [comment]
There's a lot of duplication now between `position fen ...` and `position startpos ...`. Can you merge them into one simple `if`?

**Comment by bobtie** [comment]
Sure, I'm working on it.

**Comment by thomasahle** [comment]
Looks good! Thanks!

**Pull request merged**
